/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan;

import javax.swing.JOptionPane;

/**
 *
 * @author ARVINA
 */
public class UjiKebolehan extends javax.swing.JFrame {

    /**
     * Creates new form UjiKebolehan
     */
    public UjiKebolehan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        Berat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdb1 = new javax.swing.JRadioButton();
        rdb2 = new javax.swing.JRadioButton();
        Hitung = new javax.swing.JToggleButton();
        CobaLagi = new javax.swing.JToggleButton();
        Keluar = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        bb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hasil1 = new javax.swing.JTextField();
        hasil2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(153, 11, 131, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 50, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(26, 140, 80, 30);
        getContentPane().add(Nama);
        Nama.setBounds(181, 56, 200, 40);
        getContentPane().add(Tinggi);
        Tinggi.setBounds(181, 106, 90, 30);
        getContentPane().add(Berat);
        Berat.setBounds(181, 153, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 200, 100, 40);

        rdb1.setText("Perempuan");
        getContentPane().add(rdb1);
        rdb1.setBounds(140, 200, 100, 40);

        rdb2.setText("Laki-laki");
        getContentPane().add(rdb2);
        rdb2.setBounds(266, 200, 90, 40);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        getContentPane().add(Hitung);
        Hitung.setBounds(21, 285, 100, 30);

        CobaLagi.setText("Coba Lagi");
        CobaLagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CobaLagiActionPerformed(evt);
            }
        });
        getContentPane().add(CobaLagi);
        CobaLagi.setBounds(150, 280, 90, 30);

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar);
        Keluar.setBounds(280, 280, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Berat badan ideal adalah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(32, 350, 160, 30);

        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });
        getContentPane().add(bb);
        bb.setBounds(210, 350, 90, 30);

        jLabel7.setText("kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 360, 50, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 380, 210, 40);
        getContentPane().add(hasil1);
        hasil1.setBounds(43, 423, 400, 40);

        hasil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasil2ActionPerformed(evt);
            }
        });
        getContentPane().add(hasil2);
        hasil2.setBounds(40, 470, 400, 40);

        jLabel9.setText("cm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(280, 114, 30, 20);

        jLabel10.setText("kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(280, 160, 30, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CobaLagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CobaLagiActionPerformed
        // TODO add your handling code here:
        Berat.setText("");
        Tinggi.setText("");
        bb.setText("");
        hasil1.setText("");
        hasil2.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_CobaLagiActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbActionPerformed

    private void hasil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasil2ActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        try{
        double hasil = 0;
    double tinggi = Double.valueOf(Tinggi.getText());
    double berat = Double.valueOf(Berat.getText());
    
    
    if(rdb1.isSelected()){
      hasil = (tinggi - 100)  *1;
      bb.setText(hasil+"kg");
    }else if(rdb2.isSelected()){
        hasil  = (tinggi-104)*1;
        bb.setText(hasil+"kg");
    }
   
    if(hasil<berat){
       
     
        hasil1.setText("Maaf "+Nama.getText()+", Sepertinya anda Overweight:(");
        hasil2.setText("banyaklah berolahragadan hindari makanan berkolesterol");
    }else if(hasil>berat){
        
        hasil1.setText("Maaf "+Nama.getText()+", Sepertinya anda Underweight:(");
        hasil2.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
    }else{
        
        hasil1.setText("Hallo "+Nama.getText()+",Berat badan anda sudah ideal:)");
        hasil2.setText("Lanjutkan pola makan teratur dan gaya hidup sehat:)");
    }
     } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kotak Input Belum Terisi Semua" , "Message",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_HitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UjiKebolehan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Berat;
    private javax.swing.JToggleButton CobaLagi;
    private javax.swing.JToggleButton Hitung;
    private javax.swing.JToggleButton Keluar;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JTextField bb;
    private javax.swing.JTextField hasil1;
    private javax.swing.JTextField hasil2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rdb1;
    private javax.swing.JRadioButton rdb2;
    // End of variables declaration//GEN-END:variables
}
